#include "Arduino.h"


//HTML for web front end UI  
P(daylightHTML) = 
 "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>"
  "<html xmlns='http://www.w3.org/1999/xhtml'>"
  "<head>"
  "<title>RGB Lights</title>"
  "<meta http-equiv='Content-type' content='text/html;charset=UTF-8' />"
  "<style type='text/css'>"
  "body {"
  "background-color:#fcfcfc;"
  "}"
  
  "#container {"
  "width: 1000px;"
  "min-width: 500px;"
  "margin: 50px auto;"
  "padding: 10px;"
  "}"

  "#header{"
  "width: 920px;"
  "padding: 20px;"
  "margin: 10px;"
  "background-color: #F2F2F2;"
  "}"
  
  "#slidercontainer{"
  "width: 500px;"
  "height: 320px;"
  "padding: 10px;"
  "margin: 10px;"
  "background-color: #E6E6E6;"
  "float: left;"
  "}"
  
  "#control{"
  "width: 440px;"
  "min-width: 250px;"
  "height: 500px;"
  "padding: 10px 10px;"
  "float: left;"
   "}"

  "div.const-width {"
  "font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;"
  "width: 600px;"
  "margin-left: 50px auto;"
  "}"
 
  "p.tight {"
  "padding-top: 0px;"
  "padding-bottom: 0px;"
  "margin-top: 0px;"
  "margin-bottom: 0px;"
  "}"
 
  "h1 {"
  "font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;"
  "padding-top: 0px;"
  "padding-bottom: 0px;"
  "margin-top: 0px;"
  "margin-bottom: 0px;"
  "}"
 
  ".slider, #time-spinner {"
  "margin-top: 10px;"
  "margin-bottom: 10px;"
  "}"
 
  "#time-spinner {"
  "width: 120px;"
  "}"
 
  "#transition-select {"
  "width: 150px;"
  "}"
 
"@media only screen and (max-width: 980px) {"
    
    "#container {"
        "width:100%;"
    "}"
    
    "#header {"
        "width:500px;"
        "margin: 10px auto;"
    "}"
    
   "#slidercontainer {"
        "width:500px;"
        "margin: 0px auto;"
        "padding: 20px;"
        "float:none;"
    "}"
    
    "#control {"
        "width:500px;"
        "margin:0px auto;"
        "margin-top:10px;"
        "float:none;"
    "}"


  "</style>"
  
  
  "<link href='http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css' rel='stylesheet' />"
  "<script type='text/javascript' src='http://code.jquery.com/jquery-1.9.1.js'></script>"
  "<script type='text/javascript' src='http://code.jquery.com/ui/1.10.2/jquery-ui.js'></script>"
  "<script type='text/javascript'>"
  "$(function() {"
  "var sliderOptions = {min: 0, max: 255, step: 1, stop: updateHandler};"
  "var tSpinnerOptions = {min: 0, max: 2000, stop: 1};"
  "$('#red-slider').slider(sliderOptions);"
  "$('#green-slider').slider(sliderOptions);"
  "$('#blue-slider').slider(sliderOptions);" 
  "$('#w-slider').slider(sliderOptions);"
  "$('#ww-slider').slider(sliderOptions);"
  "$('#white-slider').slider({min: 0, max: 255, step: 1, stop: whiteHandler});"
  "$('#time-spinner').spinner(tSpinnerOptions);"

  "$('#white-button')"
  ".button()"
  ".click(function() {"
  "masterHandler(255, 255, 200, 0, 0);"
  "});"
  
  "$('#full-on-button')"
  ".button()"
  ".click(function() {"
  "masterHandler(255, 255, 255, 255, 255);"
  "});"
  
  "$('#warm-daylight-button')"
  ".button()"
  ".click(function() {"
  "masterHandler(0, 0, 0, 10, 55);"
  "});"
  
  "$('#high-noon-button')"
  ".button()"
  ".click(function() {"
  "masterHandler(0, 0, 0, 55, 10);"
  "});"

  
  "$('#off-button')"
  ".button()"
  ".click(function() {"
  "masterHandler(0, 0, 0, 0, 0);"
  "});"
  
  "$('#refresh-button')" 
  ".button()"
  ".click(function() {"
  "getLightState();"
  "});"
  "getLightState();"
  "});"

  "function whiteHandler() {"
  "var whiteLightLevel = $('#white-slider').slider('values', 0);"
  "masterHandler(whiteLightLevel, whiteLightLevel, whiteLightLevel, whiteLightLevel, whiteLightLevel);"
  "}"
 
  "function masterHandler(r, g, b, w, ww) {"
  "$('#red-slider').slider('value', r);"
  "$('#green-slider').slider('value', g);"
  "$('#blue-slider').slider('value', b);"
  "$('#w-slider').slider('value', w);"
  "$('#ww-slider').slider('value', ww);"
  "updateHandler();"
  "}"
  
  "function setLights(red, green, blue, w, ww, transition, ttime) {"
  "$.post('http://172.31.142.159/service', {r: red, g: green, b: blue, w: w, ww: ww, trans: transition, time: ttime})"
  ".done(function(data) {"
  "handleXMLresponse(data);"
  "});"
  "}"
  
  "function getLightState() {"
  "$.get('http://172.31.142.159/service')"
  ".done(function(data) {"
  "handleXMLresponse(data);"
  "});"
  "}"
  
  "function handleXMLresponse(data) {"
  "var parser = new DOMParser();"
  "var doc = parser.parseFromString(data, 'text/xml');"
  "xmlDoc = $.parseXML(data);"
  "$xml = $(xmlDoc);"
  "var red = $xml.find('r').text();"
  "var green = $xml.find('g').text();"
  "var blue = $xml.find('b').text();"
  "var w = $xml.find('w').text();"
  "var ww = $xml.find('ww').text();"
  "var transition = $xml.find('lastTransition').text();"
  "var time = $xml.find('lastTime').text();"
  "$('#red-slider').slider('value', red);"
  "$('#green-slider').slider('value', green);"
  "$('#blue-slider').slider('value', blue);"
  "$('#w-slider').slider('value', w);"
  "$('#ww-slider').slider('value', ww);"
  "$('#time-spinner').spinner('value', time);"
  "var average = (parseInt(red) + parseInt(green) + parseInt(blue) + parseInt(w) + parseInt(ww)) / 5;"
  "$('#white-slider').slider('value', average);"
  "document.getElementById('transition-select').value = transition;"
  "}"
  
  "function updateHandler() {"
  "var red = $('#red-slider').slider('values', 0);"
  "var green = $('#green-slider').slider('values', 0);"
  "var blue = $('#blue-slider').slider('values', 0);"
  "var w = $('#w-slider').slider('values', 0);"
  "var ww = $('#ww-slider').slider('values', 0);"
  "var time = $( '#time-spinner' ).spinner('value');"
  "var transition = document.getElementById('transition-select').value;"
  "setLights(red, green, blue, w, ww, transition, time);"
  "}"
  
  
  
  "</script>"
  "</head>"
  "<body>"
  "<div id='container'>"
    "<div id='header'>"
        "<h1>Daylight Controll</h1></br>"
        "<div style='text-align: center'>"  
            "<a href=/rgb >RGB-Control </a> &nbsp; "
            "<a href=/service>Service</a></br>"
        "</div>"
    "</div>"
    
    "<div id='slidercontainer' id='color-sliders'>"
        "<div class='slider' id='red-slider' style='background:red'>red</div>"
        "<div class='slider' id='green-slider' style='background:green'>green</div>"
        "<div class='slider' id='blue-slider' style='background:blue'>blue</div>"
        "</br>"
        "<div class='slider' id='w-slider' style='background:#A9E2F3'>white</div>"
        "<div class='slider' id='ww-slider' style='background:#F5DA81'>warm-white</div>"
        "<div class='slider' id='white-slider'></div>"
    "</div>"
    
    "<div id='control'>"
        "<div id='time-selector'>"
            "<label>Transition Time:</label>"
            "<input id='time-spinner' name='ttime' />"
        "</div>"

        "<div id='transition-selector'>"
            "<label>Transition Type:</label>"
            "<select id='transition-select'>"
                "<option value='0'>No Transition</option>"
                "<option value='1'>Fade</option>"
                "<option value='2'>Fade Through Black</option>"
            "</select>"
        "</div>"
        
        "<div id='function-buttons'>"
            "<button id='high-noon-button'>High-Noon</button>"  
            "<button id='warm-daylight-button'>Warm-Daylight</button> </br>"  
            "<button id='white-button'>RGB-White</button>"  
            "<button id='full-on-button'>Full On</button>"
            "<button id='off-button'>Off</button>"
            "<button id='refresh-button'>Refresh</button></br>"
        "</div>"
    "</div>"
  "</div>"
  "</body>"
  "</html>";
